In [2]:
import pandas as pd

In [4]:
s2 = pd.Series([90, 80, 70], index = ["국어", "영어", "수학"])
print(s2)
display(s2)

국어    90
영어    80
수학    70
dtype: int64

국어    90
영어    80
수학    70
dtype: int64

In [5]:
display(s2.loc["영어"])
display(s2.iloc[1])

np.int64(80)

np.int64(80)

In [9]:
df1 = pd.DataFrame({
            "이름" : ["홍길동", "김철수", "이영희"],
            "나이" : [20, 30, 25],
            "점수" : [90, 80, 95]}, index = ["첫번째", "두번쨰", "세번째"])

In [10]:
df1

      이름  나이  점수
첫번째  홍길동  20  90
두번쨰  김철수  30  80
세번째  이영희  25  95

In [11]:
df2 = pd.DataFrame({
            "나이" : [20, 30, 25],
            "점수" : [90, 80, 95]}, index = ["홍길동", "김철수", "이영희"])
df2

     나이  점수
홍길동  20  90
김철수  30  80
이영희  25  95