In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "이름": ["김민수", "이서연", "박지훈"],
    "점수": [80, 90, 75]
})

# 열 1개 선택 → Series
s = df["점수"]

display(s)
display(type(s))


# 열 1개를 리스트로 선택 → DataFrame
df2 = df[["점수"]]

display(df2)
display(type(df2))

0    80
1    90
2    75
Name: 점수, dtype: int64

pandas.Series

   점수
0  80
1  90
2  75

pandas.DataFrame

In [3]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "직원ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "이름": ["김민준", "이서연", "박지훈", "최유진",
           "정현우", "강수빈", "조민서", "윤도현"],
    "부서": ["개발", "영업", "개발", "인사",
           "영업", "개발", "영업", "인사"],
    "성별": ["남", "여", "남", "여", "남", "여", "여", "남"],
    "매출": [850, 920, np.nan, 780, 1200, 650, 920, np.nan],
    "근무시간": [160, 172, 168, 155, 180, 150, 172, 158],
    "등급": ["B", "A", "B", "C", "A", "C", "A", None],
    "입사년도": [2020, 2019, 2021, 2022, 2018, 2023, 2019, 2022]
})

display(df)

   직원ID   이름  부서 성별      매출  근무시간   등급  입사년도
0   101  김민준  개발  남   850.0   160    B  2020
1   102  이서연  영업  여   920.0   172    A  2019
2   103  박지훈  개발  남     NaN   168    B  2021
3   104  최유진  인사  여   780.0   155    C  2022
4   105  정현우  영업  남  1200.0   180    A  2018
5   106  강수빈  개발  여   650.0   150    C  2023
6   107  조민서  영업  여   920.0   172    A  2019
7   108  윤도현  인사  남     NaN   158  NaN  2022

In [4]:
# 1) 기본정보
s = df["매출"]
display("s type:",type(s))

display(df["매출"].head(2)) # 기본값 5
display(df["매출"].tail(2))

display(df["매출"].info())
display(df["매출"].describe())
display(df["등급"].describe())

's type:'

pandas.Series

0    850.0
1    920.0
Name: 매출, dtype: float64

6    920.0
7      NaN
Name: 매출, dtype: float64

<class 'pandas.Series'>
RangeIndex: 8 entries, 0 to 7
Series name: 매출
Non-Null Count  Dtype
--------------  -----
6 non-null      float64
dtypes: float64(1)
memory usage: 196.0 bytes

None

count       6.000000
mean      886.666667
std       183.920273
min       650.000000
25%       797.500000
50%       885.000000
75%       920.000000
max      1200.000000
Name: 매출, dtype: float64

count     7
unique    3
top       A
freq      3
Name: 등급, dtype: object

In [7]:
df["부서"].mode()

0    개발
1    영업
Name: 부서, dtype: str

In [8]:
# 데이터 개수
# Series.count()메서드 vs len()함수
display(df["매출"].count()) # NaN 제외
display(len(df["매출"])) # NaN 포함

np.int64(6)

8

In [9]:
# 3) 고유값 - 범주형 데이터에 주로 사용
display(df["성별"].unique())
display(df["부서"].unique())

# 고유값 개수
display(df["성별"].nunique())
display(df["부서"].nunique())

<StringArray>
['남', '여']
Length: 2, dtype: str

<StringArray>
['개발', '영업', '인사']
Length: 3, dtype: str

2

3

In [10]:
# 4) 빈도 - 범주형 데이터에 주로 사용
display(df["성별"].value_counts())
display(df["부서"].value_counts())

성별
남    4
여    4
Name: count, dtype: int64

부서
개발    3
영업    3
인사    2
Name: count, dtype: int64

In [11]:
# 5) 결측치 - 결측값이면 True
display(df["매출"].isna())
display(df["매출"].isnull())

display(df["매출"].notna()) # not na
display(df["매출"].notnull()) # not null

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
Name: 매출, dtype: bool

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
Name: 매출, dtype: bool

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: 매출, dtype: bool

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: 매출, dtype: bool

In [12]:
# fillna - 결측값 대체
sales = df["매출"]
# 평균값으로 대체
sales = sales.fillna(sales.mean())
display(sales)

0     850.000000
1     920.000000
2     886.666667
3     780.000000
4    1200.000000
5     650.000000
6     920.000000
7     886.666667
Name: 매출, dtype: float64

In [13]:
# dropna - 결측값 제거
sales = df["매출"]
sales_clean = sales.dropna()
display(sales_clean)

0     850.0
1     920.0
3     780.0
4    1200.0
5     650.0
6     920.0
Name: 매출, dtype: float64

In [14]:
# 6) 정렬 - 결측치는 오름/내림 관계없이 마지막
display(df["매출"].sort_values(ascending=False))
display(df["매출"].sort_values())

# 문자값도 정렬
display(df["이름"].sort_values())
# 값이 아닌 인덱스 순으로 정렬
display(df["이름"].sort_index(ascending=False))

4    1200.0
1     920.0
6     920.0
0     850.0
3     780.0
5     650.0
2       NaN
7       NaN
Name: 매출, dtype: float64

5     650.0
3     780.0
0     850.0
1     920.0
6     920.0
4    1200.0
2       NaN
7       NaN
Name: 매출, dtype: float64

5    강수빈
0    김민준
2    박지훈
7    윤도현
1    이서연
4    정현우
6    조민서
3    최유진
Name: 이름, dtype: str

7    윤도현
6    조민서
5    강수빈
4    정현우
3    최유진
2    박지훈
1    이서연
0    김민준
Name: 이름, dtype: str

In [15]:
# 7) 문자열 - str속성 사용
display(df["이름"].str.contains("박"))

names1 = pd.Series([
    " 김민준 ",
    " 이서연",
    "박 지훈 ",
    " 최유진 "
])

names2 = names1.str.strip() # 앞뒤공백제거
display(names2)

names3 = names1.str.replace(" ","") # 공백을 빈문자열로 변경
display(names3)

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7    False
Name: 이름, dtype: bool

0     김민준
1     이서연
2    박 지훈
3     최유진
dtype: str

0    김민준
1    이서연
2    박지훈
3    최유진
dtype: str

In [16]:
# 8) 형변환
employee_id = df["직원ID"]
print()
print(employee_id.info())
employee_id = employee_id.astype(str)
print()
print(employee_id.info())

<class 'pandas.Series'>
RangeIndex: 8 entries, 0 to 7
Series name: 직원ID
Non-Null Count  Dtype
--------------  -----
8 non-null      int64
dtypes: int64(1)
memory usage: 196.0 bytes
None

<class 'pandas.Series'>
RangeIndex: 8 entries, 0 to 7
Series name: 직원ID
Non-Null Count  Dtype
--------------  -----
8 non-null      str
dtypes: str(1)
memory usage: 196.0 bytes
None

In [17]:
gender = df["성별"]
print()
print(gender.info())
gender = gender.astype("category")
print()
print(gender.info())

<class 'pandas.Series'>
RangeIndex: 8 entries, 0 to 7
Series name: 성별
Non-Null Count  Dtype
--------------  -----
8 non-null      str
dtypes: str(1)
memory usage: 196.0 bytes
None

<class 'pandas.Series'>
RangeIndex: 8 entries, 0 to 7
Series name: 성별
Non-Null Count  Dtype
--------------  -----
8 non-null      category
dtypes: category(1)
memory usage: 156.0 bytes
None

In [18]:
# 숫자로 변경
sales = pd.Series(["850", "920", "780", "잘못된값"])
# sales = pd.to_numeric(sales) ERROR
# errors="coerce"는 숫자로 변환할 수 없는 값을 NaN으로 바꾼다.
sales = pd.to_numeric(sales, errors="coerce")
display(sales)

sales = pd.Series(["A", "B", "C"])
sales = pd.to_numeric(sales, errors="coerce")
display(sales)

0    850.0
1    920.0
2    780.0
3      NaN
dtype: float64

0   NaN
1   NaN
2   NaN
dtype: float64

In [19]:
# 9) 조건처리
# where(조건) True -> 원래값, False -> NaN
# 매출이 800 이상인 값은 그대로 두고, 800 미만은 NaN으로 만든다.
result = df["매출"].where(df["매출"] >= 800)
display(result)

# mask() — 조건에 맞는 값 변경
# 매출이 800 미만인 값을 0으로 변경한다.
result = df["매출"].mask(df["매출"] < 800, 0)
display(result)

0     850.0
1     920.0
2       NaN
3       NaN
4    1200.0
5       NaN
6     920.0
7       NaN
Name: 매출, dtype: float64

0     850.0
1     920.0
2       NaN
3       0.0
4    1200.0
5       0.0
6     920.0
7       NaN
Name: 매출, dtype: float64

In [20]:
# 10) 중복 여부 확인, 중복 제거
display(df["부서"].duplicated())

unique_department = df["부서"].drop_duplicates()
display(unique_department)

0    False
1    False
2     True
3    False
4     True
5     True
6     True
7     True
Name: 부서, dtype: bool

0    개발
1    영업
3    인사
Name: 부서, dtype: str

In [21]:
# 11) 데이터 값 변경 

# 특정 값만 변경
department_eng1 = df["부서"].replace({
    "개발": "Development"
})
display(department_eng1)


# 전체 시리즈를 변경 - 맵핑되지 않은 값은 NaN으로 변경된다. -> 전체를 변경시에만 사용
department_eng2 = df["부서"].map({
    "개발": "Development"
})
display(department_eng2)

# apply()메서드에 함수를 인자로 전달(고차함수)
# 고차함수 : https://cafe.naver.com/jjdev/19084
def sales_grade(value):
    if pd.isna(value):
        return "미집계"
    elif value >= 1000:
        return "우수"
    elif value >= 800:
        return "보통"
    else:
        return "낮음"

grade = df["매출"].apply(sales_grade) # 시리즈의 값들에 순차적으로 sales_grade함수를 적용
display(grade)

0    Development
1             영업
2    Development
3             인사
4             영업
5    Development
6             영업
7             인사
Name: 부서, dtype: str

0    Development
1            NaN
2    Development
3            NaN
4            NaN
5    Development
6            NaN
7            NaN
Name: 부서, dtype: str

0     보통
1     보통
2    미집계
3     낮음
4     우수
5     낮음
6     보통
7    미집계
Name: 매출, dtype: str

In [22]:
# 12) 누적
display(df["매출"].cumsum()) # NaN제외

display(df["매출"].cummax()) # 슬라이딩 비교 후 큰값만 남기. NaN제외

display(df["매출"].cummin()) # 슬라이딩 비교 후 작은값만 남기. NaN제외

# 누적곱
growth = pd.Series([1.1, 1.2, 0.9, 1.1])
display(growth.cumprod())

0     850.0
1    1770.0
2       NaN
3    2550.0
4    3750.0
5    4400.0
6    5320.0
7       NaN
Name: 매출, dtype: float64

0     850.0
1     920.0
2       NaN
3     920.0
4    1200.0
5    1200.0
6    1200.0
7       NaN
Name: 매출, dtype: float64

0    850.0
1    850.0
2      NaN
3    780.0
4    780.0
5    650.0
6    650.0
7      NaN
Name: 매출, dtype: float64

0    1.1000
1    1.3200
2    1.1880
3    1.3068
dtype: float64

In [23]:
# 13) 시계열 데이터에 쉬프트 연산

# 값 이동 : 한칸 이동(0번째 값은 NaN으로 대체)
display(df["매출"].shift())
# 값 차이 : 이전값과의 차이(0번째 값은 앞에 값이 없으니 NaN)
display(df["매출"].diff())

# 이전 값 대비 몇% 증가/감소 100->110이면 0.1 10%, 100->90 -0.1, 100->100 0
display(df["매출"].pct_change())

0       NaN
1     850.0
2     920.0
3       NaN
4     780.0
5    1200.0
6     650.0
7     920.0
Name: 매출, dtype: float64

0      NaN
1     70.0
2      NaN
3      NaN
4    420.0
5   -550.0
6    270.0
7      NaN
Name: 매출, dtype: float64

0         NaN
1    0.082353
2         NaN
3         NaN
4    0.538462
5   -0.458333
6    0.415385
7         NaN
Name: 매출, dtype: float64

In [24]:
# 14) 기타
# 값 포함 isin()
display(df["성별"].isin(["male"]))
display(df["성별"].isin(["남"]))
display(df["성별"].isin(["남", "여"]))

# 무작위 추출 sample()
display(df["이름"].sample(3, random_state=42)) 
# random_state값이 동일하면 동일한 랜덤 알고리즘을 적용 -> 같은값
display(df["이름"].sample(3, random_state=42))
display(df["이름"].sample(3, random_state=0))

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: 성별, dtype: bool

0     True
1    False
2     True
3    False
4     True
5    False
6    False
7     True
Name: 성별, dtype: bool

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
Name: 성별, dtype: bool

1    이서연
5    강수빈
0    김민준
Name: 이름, dtype: str

1    이서연
5    강수빈
0    김민준
Name: 이름, dtype: str

6    조민서
2    박지훈
1    이서연
Name: 이름, dtype: str

In [25]:
# 시리즈를 데이터프레임으로 변경
name = df["이름"]
display(type(name))
display(name)

name_df = name.to_frame()
display(type(name_df))
display(name_df)

pandas.Series

0    김민준
1    이서연
2    박지훈
3    최유진
4    정현우
5    강수빈
6    조민서
7    윤도현
Name: 이름, dtype: str

pandas.DataFrame

    이름
0  김민준
1  이서연
2  박지훈
3  최유진
4  정현우
5  강수빈
6  조민서
7  윤도현

In [26]:
# 복사, equal
sales1 = df["매출"].copy()
sales2 = df["매출"].copy()
sales3 = pd.Series([850, 920, np.nan, 780, 1200, 650, 920, np.nan])
print(sales1.equals(sales2))
print(sales1.equals(sales3))

sales3[0] = 1000
print(sales1.equals(sales3))

True
True
False